### ISSUE TITLE
Undefined method '[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by EdgarOrtegaRamirez** [charly-palencia/blueprint-agreement#1]
**Behavior**

Error is raised after running the test suite, there was no server running.

**How to reproduce?**

Run minitest using `rake` having the gem installed but without using it.

**Where?**

https://github.com/charly-palencia/blueprint-agreement/blob/master/lib/blueprint_agreement.rb#L49

**Comment by charly-palencia** [comment]
@EdgarOrtegaRamirez  good catch, thanks!

I pushed a fixed for this issues.
